services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /opt/contrast/work:/work
    environment:
      TZ: Asia/Tokyo
    working_dir: /app
    command: python create_org.py

