services:
  playwright_dl_lib_data:
    container_name: playwright_dl_lib_data
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /opt/contrast/work:/work
    environment:
      TZ: Asia/Tokyo
      CONTRAST_HUB_USERNAME: ${HUB_USERNAME:?err}
      CONTRAST_HUB_PASSWORD: ${HUB_PASSWORD:?err}
    env_file:
      - lib_data.env
    working_dir: /app
    command: python download_library_data.py

