services:
  log_monitor:
    container_name: log_monitor
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Tokyo
      - INSTANCE_ID=${INSTANCE_ID:?err}
      - INSTANCE_TYPE=${INSTANCE_TYPE:?err}
      - EIP=${EIP:?err}
      - PIP=${PIP:?err}
      - SHL_FILE_NAME=${SHL_FILE_NAME:?err}
      - LIC_FILE_NAME=${LIC_FILE_NAME:?err}
      - LIB_FILE_NAME=${LIB_FILE_NAME:?err}
      - LOG_FILE_PATH=/work/server.log
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/contrast/logs/server.log:/work/server.log:ro
      - ./log_monitor.py:/app/log_monitor.py
    command: ["python", "/app/log_monitor.py"]
    restart: "no"

