services:
  playwright_hub_off:
    container_name: playwright_hub_off
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /opt/contrast/work:/work
    environment:
      TZ: Asia/Tokyo
    working_dir: /app
    command: python hub_off.py

