services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      CONTRAST_HUB_USERNAME: ${HUB_USERNAME:?err}
      CONTRAST_HUB_PASSWORD: ${HUB_PASSWORD:?err}
    env_file:
      - lib_date.env
    working_dir: /app
    command: python download_library_data.py

