import re
import time
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=True)
    context = browser.new_context()
    page = context.new_page()
    page.goto("http://contrast.nginx/Contrast/static/ng/index.html#/pages/signin")
    page.get_by_test_id("username-email").click()
    page.get_by_test_id("username-email").fill("contrast_superadmin@contrastsecurity.com")
    page.get_by_test_id("password").click()
    page.get_by_test_id("password").fill("default1!")
    page.get_by_test_id("log-in-button").click()
    page.get_by_role("button", name="Add Organization").click()
    page.locator("input[name=\"name\"]").click()
    page.locator("input[name=\"name\"]").fill("SampleOrg")
    page.locator("input[name=\"name\"]").press("Tab")
    page.locator(".switch > i").first.click()
    page.locator("react-oss-feature-switch i").click()
    page.get_by_text("Automatically apply allocated").click()
    page.get_by_role("checkbox", name="Assess (Application licenses)").check()
    page.get_by_text("Protect (Server licenses)").click()
    page.get_by_text("×").click()
    page.get_by_test_id("autocomplete-0").click()
    page.get_by_role("option", name="日本語").click()
    page.get_by_label("Select box activate").first.click()
    page.get_by_role("link", name="yyyy/MM/dd").click()
    page.locator("#settings-org-timezone i").first.click()
    page.get_by_role("link", name="(GMT+09:00) Osaka, Sapporo,").click()
    page.get_by_text("Enable Duplicate").click()
    page.get_by_text("Display Auto-Verification").click()
    page.get_by_text("Enable DISA STIG Checklist").click()
    page.get_by_text("Enable Vulnerability Trends").click()
    page.locator("react-app-library-status-superadmin-org-toggle i").click()
    page.locator("input[name=\"adminEmail\"]").click()
    page.locator("input[name=\"adminEmail\"]").fill("ichiro.sato@contrastsecurity.com")
    page.locator("input[name=\"adminFirstName\"]").click()
    page.locator("input[name=\"adminFirstName\"]").fill("Ichiro")
    page.locator("input[name=\"adminLastName\"]").click()
    page.locator("input[name=\"adminLastName\"]").fill("Sato")
    page.locator("input[name=\"adminPassword\"]").click()
    page.locator("input[name=\"adminPassword\"]").fill("default1!")
    page.locator("input[name=\"confirmpassword\"]").click()
    page.locator("input[name=\"confirmpassword\"]").fill("default1!")
    page.get_by_role("button", name="Add", exact=True).click()
    page.get_by_role("textbox", name="Find Organization").click()
    page.get_by_role("textbox", name="Find Organization").fill("Sample")
    time.sleep(3)
    page.get_by_role("link", name="Assess").click()
    page.get_by_text("Add more licenses").click()
    page.get_by_placeholder("How many licenses?").click()
    page.get_by_placeholder("How many licenses?").fill("3")
    page.get_by_role("button", name="Allocate").click()
    page.get_by_role("link", name="Protect").click()
    page.get_by_text("Change license allocation").click()
    page.get_by_role("spinbutton", name="License allocation").click()
    page.get_by_role("spinbutton", name="License allocation").fill("3")
    page.get_by_test_id("license-summary-modal-footer-primary-button").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
