services:
  playwright_create_org:
    image: playwright:latest
    container_name: playwright_create_org
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /opt/contrast/work:/work
    environment:
      TZ: Asia/Tokyo
    working_dir: /app
    command: python create_org.py

